
POST http://localhost:3001/api/messages
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbWkiLCJpZCI6IjVkYmQ1YjZkZDk3YzNmMTVkMDJlZTBlNSIsImlhdCI6MTU3MjY5MTEyMn0.FdLLmy1dCRq3ZvGrSsSYQBkAsoKfNTnAKX_t_OGktME
Content-Type: application/json

{
  "title": "first message",
  "content": "something wicked",
  "author": "5dbd5b6dd97c3f15d02ee0e5",
  "createdAt": "Sat Nov 02 2019 13:33:59 GMT+0200 (Eastern European Standard Time)",
  "receiver": "5dbd5b56d97c3f15d02ee0e4"
}